import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from 'styles/Home.module.css'
import Button from 'components/Button'

import {loginWithGitHub } from 'firebase/client'

import { useRouter } from 'next/router'
import useUser, { USER_STATES } from 'hooks/useUser'

export default function Home() {
  
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/home')    
  }, [user])
  
  const handleClick = () => {
      loginWithGitHub().then(user => {
        const {avatar, userName, url} = user
        //setUser(user)
        console.log('UserData', user)
      }).catch(err => {
        console.log(err)
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.initial_section}> 
          <img className={styles.img} src='/devter-logo.png' alt='Logo'></img>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Devter!</a>
          </h1>
          <div>
            {
              user === USER_STATES.NOT_LOGGED &&
                <Button onClick={handleClick}>
                  Login with GitHub
                </Button>                 
            }
            {user === USER_STATES.NOT_KNOWN && <img src={'/spinner.gif'}/>}
          </div>
        </section>
      </main>
    </div>
  )
}
